### ISSUE TITLE
Failed to parse query [1981-391/1]

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#1229]
Expect this is related to the recent changes to better support Boolean queries
https://github.com/TheScienceMuseum/collectionsonline/pull/1228

Looks like we need to escape reserved chars (like the /)
- https://stackoverflow.com/questions/36467500/do-reserved-characters-need-to-be-escaped-in-an-elasticsearch-query
- https://stackoverflow.com/questions/48524864/failed-to-parse-query-using-elastic-search-api

```
Service Unavailable
[query_shard_exception] Failed to parse query [1981-391/1], with { index_uuid="ZZZ" & index="smg" }

Error: [query_shard_exception] Failed to parse query [1981-391/1], with { index_uuid="ZZZ" & index="smg" }
    at respond (/Users/jamieunwin/projects/collectionsonline/node_modules/elasticsearch/src/lib/transport.js:308:15)
    at checkRespForFailure (/Users/jamieunwin/projects/collectionsonline/node_modules/elasticsearch/src/lib/transport.js:267:7)
    at HttpConnector.<anonymous> (/Users/jamieunwin/projects/collectionsonline/node_modules/elasticsearch/src/lib/connectors/http.js:165:7)
    at IncomingMessage.wrapper (/Users/jamieunwin/projects/collectionsonline/node_modules/lodash/lodash.js:4935:19)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by iteles** [comment]
Jamie reviewed and appears to no longer be a bug. Fixed by #1231
