### ISSUE TITLE
CO2.0: Error with nested child record example page

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#1532]
Computer Peripherals (2017-170) - record published, but error with new website codebase (Cannot read properties of undefined (reading 'find') in lib/transforms/json-to-html-data.js
http://localhost:8000/objects/co8608255

(same record on live https://collection.sciencemuseumgroup.org.uk/objects/co8608255)

TypeError: Cannot read properties of undefined (reading 'find')
    at getChildTitle (/Users/jamieunwin/projects/collectionsonline/lib/transforms/json-to-html-data.js:776:30)
    at /Users/jamieunwin/projects/collectionsonline/lib/transforms/json-to-html-data.js:756:21
    at Array.map (<anonymous>)
    at getChildRecords (/Users/jamieunwin/projects/collectionsonline/lib/transforms/json-to-html-data.js:754:25)

**Comment by jamieu** [comment]
Fixed on dev
