### ISSUE TITLE
CO2.0: Error on MPH page [showstopper]

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#1551]
http://localhost:8000/objects/co8401256/xperia-z2-tablet-computer

_(same as this one too http://localhost:8000/objects/co52335/james-watts-garret-workshop-used-1790-1819-workshop-work-space ?)_

This record on live
https://collection.sciencemuseumgroup.org.uk/objects/co8401256/

![1dbc97ea-d061-4dbe-afc2-c73f835df486](https://github.com/TheScienceMuseum/collectionsonline/assets/91365/5ff3c0e2-9a09-445e-9c59-f9a7d78384fb)

```
Service Unavailable
unavailable

Error: unavailable
    at handler (/Users/jamieunwin/projects/collectionsonline/routes/object.js:60:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exports.Manager.execute (/Users/jamieunwin/projects/collectionsonline/node_modules/@hapi/hapi/lib/toolkit.js:60:28)
    at async internals.handler (/Users/jamieunwin/projects/collectionsonline/node_modules/@hapi/hapi/lib/handler.js:46:20)
    at async exports.execute (/Users/jamieunwin/projects/collectionsonline/node_modules/@hapi/hapi/lib/handler.js:31:20)
    at async Request._lifecycle (/Users/jamieunwin/projects/collectionsonline/node_modules/@hapi/hapi/lib/request.js:370:32)
    at async Request._execute (/Users/jamieunwin/projects/collectionsonline/node_modules/@hapi/hapi/lib/request.js:280:9)
```

**Comment by jamieu** [comment]
Fixed on dev :-)
