### ISSUE TITLE
CO2.0: Error Cannot read properties of null 

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#1569]
http://localhost:8000/objects/co418181

TypeError: Cannot read properties of null (reading 'data')
    at /Users//projects/collectionsonline/lib/transforms/json-to-html-data.js:764:49
    at Array.map (<anonymous>)
    at getChildRecords (/Users//projects/collectionsonline/lib/transforms/json-to-html-data.js:763:25)
    at module.exports (/Users//projects/collectionsonline/lib/transforms/json-to-html-data.js:35:24)
    at module.exports (/Users//projects/collectionsonline/routes/route-helpers/response.js:8:22)
    at handler (/Users//projects/collectionsonline/routes/object.js:62:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async exports.Manager.execute (/Users//projects/collectionsonline/node_modules/@hapi/hapi/lib/toolkit.js:60:28)

**Comment by jamieu** [comment]
Closing, seems to work fine now
