### ISSUE TITLE
Bug: error after http connection dropped

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#351]
This might be (almost certainly is) a side-effect my flaky connection, but getting the error below..
/people/smgc-people-37037

![Uploading Screen Shot 2016-09-07 at 11.20.45.png…]()

**Comment by SimonLab** [comment]
@jamieu I don't think the screenshot is working

**Comment by jamieu** [comment]
Almost certainly related to a dropped connection..

```
Internal Server Error
An internal server error occurred

TypeError: Uncaught error: Cannot read property 'push' of undefined
    at /var/app/current/lib/sort-related-items.js:15:25
    at Array.forEach (native)
    at module.exports.related.forEach (/var/app/current/lib/sort-related-items.js:13:11)
    at /var/app/current/routes/person.js:59:24
    at /var/app/current/lib/get-related-items.js:41:14
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at respond (/var/app/current/node_modules/elasticsearch/src/lib/transport.js:310:9)
    at checkRespForFailure (/var/app/current/node_modules/elasticsearch/src/lib/transport.js:248:7)
    at HttpConnector.<anonymous> (/var/app/current/node_modules/elasticsearch/src/lib/connectors/http.js:164:7)
```
