### ISSUE TITLE
 Uncaught error: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#612]
On this page..
http://collectionsonline-staging.eu-west-1.elasticbeanstalk.com/objects/co8223538/filming-ill-stick-to-you-gelatin-silver-print-photograph

Linked to from here..
http://collectionsonline-staging.eu-west-1.elasticbeanstalk.com/search?filter%5Btype%5D=photograph&page%5Bsize%5D=50&page%5Btype%5D=search

```
Internal Server Error
An internal server error occurred

TypeError: Uncaught error: Cannot read property 'match' of undefined
    at Object.keys.forEach.el (/var/app/current/lib/transforms/json-to-html-data.js:427:28)
    at Array.forEach (native)
    at formatLicense (/var/app/current/lib/transforms/json-to-html-data.js:426:25)
    at data.attributes.multimedia.map.e (/var/app/current/lib/transforms/json-to-html-data.js:411:19)
    at Array.map (native)
    at getImages (/var/app/current/lib/transforms/json-to-html-data.js:403:41)
    at module.exports (/var/app/current/lib/transforms/json-to-html-data.js:25:18)
    at /var/app/current/routes/object.js:71:24
    at elastic.search (/var/app/current/lib/get-similar-objects.js:49:14)
    at bound (domain.js:280:14)
```

http://collectionsonline-staging.eu-west-1.elasticbeanstalk.com/objects/co8223538/filming-ill-stick-to-you-gelatin-silver-print-photograph

**Comment by Danwhy** [comment]
looks like a problem with the license, I'll fix it alongside the filtering

**Comment by iteles** [comment]
Linked to #641

**Comment by jamieu** [comment]
👍
