### ISSUE TITLE
Uncaught error: Cannot read property 'find' of undefined

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#743]
http://collection.sciencemuseum.org.uk/objects/co205823/midland-railway-composite-carriage-railway-carriage

Also a similar error (although a lack of good logs / details on this one) when clicking through from the first results on this SERP page..
https://collection.sciencemuseum.org.uk/search?q=Chemins%20de%20Fer

```
170111/140841.135, [response] http://Jamies-MacBook-Pro.local:8000: post /analytics {} 204 (5ms)
170111/140841.141, [response] http://Jamies-MacBook-Pro.local:8000: get /objects/co206023 {"ajax":"true"} 200 (116ms)
```

```
TypeError: Uncaught error: Cannot read property 'find' of undefined
    at /Users/jamie/projects/collectionsonline/lib/transforms/json-to-html-data.js:387:32
    at Array.map (native)
    at getImages (/Users/jamie/projects/collectionsonline/lib/transforms/json-to-html-data.js:376:41)
    at module.exports (/Users/jamie/projects/collectionsonline/lib/transforms/json-to-html-data.js:27:18)
    at /Users/jamie/projects/collectionsonline/routes/object.js:68:24
    at /Users/jamie/projects/collectionsonline/lib/get-similar-objects.js:52:14
    at bound (domain.js:287:14)
    at runBound (domain.js:300:12)
    at respond (/Users/jamie/projects/collectionsonline/node_modules/elasticsearch/src/lib/transport.js:310:9)
    at checkRespForFailure (/Users/jamie/projects/collectionsonline/node_modules/elasticsearch/src/lib/transport.js:248:7)

```

**Comment by nelsonic** [comment]
@jamieu how did you get on with checking the logs?

**Comment by jamieu** [comment]
Yes, added some log output above.
