### ISSUE TITLE
Update tests to reflect new index and brand-updates branch

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#875]
Due to the number of new records in the upcoming/updated index we may need to update some tests - in particular the two Selenium tests below.

```
 TEST FAILURE:  2 assertions failed, 104 passed. (3m 44s)

 ✖ disactive-facet.clienttest

   - Disactive Facet (6.787s)
   Timed out while waiting for element <.filter__box[value=photographer]> to be present for 3000 milliseconds.  - expected "visible" but got: "not found"
       at Object.module.exports.Disactive Facet (/Users/jamie/projects/collectionsonline/test/client/disactive-facet.clienttest.js:9:8)

 ✖ sticky-filters.clienttest

   - Sticky filters persist after new search (10.042s)
   Testing if the URL equals "http://localhost:8000/search/museum/National%20Railway%20Museum/gallery/Great%20Hall?q=electric".  - expected "http://localhost:8000/search/museum/National%20Railway%20Museum/gallery/Great%20Hall?
```q=electric" but got: "http://localhost:8000/search?q=electric"
       at Object.module.exports.Sticky filters persist after new search (/Users/jamie/projects/collectionsonline/test/client/sticky-filters.clienttest.js:14:15)
```

**Comment by shouston3** [comment]
@Danwhy I'm having issues running these locally, after installing the kit, I'm arriving at this page: https://www.java.com/en/download/faq/chrome.xml

Saying that my chrome version no longer supports this 😢 

I don't fancy fixing these from travis outputs, maybe we can pair on this tomorrow or something?
