### ISSUE TITLE
Issue loading people/agents/makers via AJAX on IE11

### ISSUE THREAD

**Issue by jamieu** [TheScienceMuseum/collectionsonline#929]
This is a critical for us as IE11 is the standard browser here.

See screenshot, the error happens whenever you click on the agent name in IE or even simply search for an agent/person. 

Only affects agents/people.

Search for a maker/person or clic on the maker link below in IE11
http://collection.sciencemuseum.org.uk/objects/co67823/portrait-of-ada-countess-of-lovelace-watercolour-drawing-portrait

Looks like `.includes` in IE11 is the cause?
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes#Browser_compatibility
- https://stackoverflow.com/questions/31119300/ie11-object-doesnt-support-property-or-method-includes-javascript-window
- https://stackoverflow.com/questions/31221341/ie-does-not-support-includes-method 

```
TypeError: Object doesn't support property or method 'includes'
   {
      [functions]: ,
      __proto__: { },
      description: "Object doesn't support property or method 'includes'",
      message: "Object doesn't support property or method 'includes'",
      name: "TypeError",
      number: -2146827850,
      stack: "TypeError: Object doesn't support property or method 'includes'
   at getBirthDate (http://collection.sciencemuseum.org.uk/bundle.js:5:20058)
   at getDate (http://collection.sciencemuseum.org.uk/bundle.js:5:19629)
   at createResult (http://collection.sciencemuseum.org.uk/bundle.js:6:9105)
   at module.exports (http://collection.sciencemuseum.org.uk/bundle.js:6:7219)
   at Anonymous function (http://collection.sciencemuseum.org.uk/bundle.js:1:29999)
   at Anonymous function (http://collection.sciencemuseum.org.uk/bundle.js:1:8671)
   at tryCallOne (http://collection.sciencemuseum.org.uk/bundle.js:24:29558)
   at Anonymous function (http://collection.sciencemuseum.org.uk/bundle.js:24:31014)
   at flush (http://collection.sciencemuseum.org.uk/bundle.js:25:8059)"
   }
```

<img width="1040" alt="screen shot 2017-07-07 at 17 28 59" src="https://user-images.githubusercontent.com/91365/27967143-d0501f76-6339-11e7-9b55-555949467d80.png">

**Comment by jamieu** [comment]
LGTM 👍
